server:
  error:
    #include-stacktrace: never
    include-stacktrace: on_trace_param


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movement?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update