server:
  error:
    #include-stacktrace: never
    include-stacktrace: on_trace_param


spring:
  application:
    name: springboot-pfm
  datasource:
    url: jdbc:mysql://localhost:3306/movement
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

